#!/usr/bin/env python3
"""Generate C test-vector data (vectors.inc) from testvectors/*.json.

Usage: gen_vectors.py <output.inc>

Reads ../../testvectors/{ff1_nist.json,v1.json} relative to this script and
emits a self-contained C include file with plain positional aggregate
initializers (valid in both C11 and C++17).
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VECTORS_DIR = REPO_ROOT / "testvectors"


def c_str(s):
    if s is None:
        return "NULL"
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= ord(ch) <= 0x7E:
            out.append(ch)
        else:
            out.append("\\x%02x" % ord(ch))
    return '"' + "".join(out) + '"'


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_vectors.py <output.inc>")
    out_path = Path(sys.argv[1])

    nist = json.loads((VECTORS_DIR / "ff1_nist.json").read_text())
    v1 = json.loads((VECTORS_DIR / "v1.json").read_text())

    lines = []
    w = lines.append
    w("/* Generated by gen_vectors.py from the testvectors JSON files. */")
    w("/* Do not edit by hand. */")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("typedef struct {")
    w("    int sample;")
    w("    const char *key_hex;")
    w("    unsigned radix;")
    w("    const char *tweak_hex;")
    w("    const char *plaintext;")
    w("    const char *ciphertext;")
    w("} tv_nist_t;")
    w("")
    w("static const tv_nist_t TV_NIST[] = {")
    for vec in nist["vectors"]:
        w(
            "    { %d, %s, %d, %s, %s, %s },"
            % (
                vec["sample"],
                c_str(vec["key_hex"]),
                vec["radix"],
                c_str(vec["tweak_hex"]),
                c_str(vec["plaintext"]),
                c_str(vec["ciphertext"]),
            )
        )
    w("};")
    w("#define TV_NIST_COUNT (sizeof TV_NIST / sizeof TV_NIST[0])")
    w("")
    w("typedef struct {")
    w("    uint64_t n;")
    w("    const char *code;")
    w("} tv_pair_t;")
    w("")
    w("typedef struct {")
    w("    const char *input;")
    w("    uint64_t n;")
    w("} tv_norm_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int min_length;")
    w("    int max_length;")
    w("    const char *domain;")
    w("    const tv_pair_t *vectors;")
    w("    size_t n_vectors;")
    w("    const char *const *invalid_codes;")
    w("    size_t n_invalid_codes;")
    w("    const tv_norm_t *normalize;")
    w("    size_t n_normalize;")
    w("} tv_config_t;")
    w("")

    configs = v1["configs"]
    for i, cfg in enumerate(configs):
        counters = [int(vec["n"]) for vec in cfg["vectors"]]
        assert all(0 <= n < 2**63 for n in counters), cfg["name"]
        w("static const tv_pair_t TV_V1_%d_PAIRS[] = {" % i)
        for vec in cfg["vectors"]:
            w("    { UINT64_C(%d), %s }," % (int(vec["n"]), c_str(vec["code"])))
        w("};")
        if cfg.get("invalid_codes"):
            w("static const char *const TV_V1_%d_INVALID[] = {" % i)
            for code in cfg["invalid_codes"]:
                w("    %s," % c_str(code))
            w("};")
        if cfg.get("normalize"):
            w("static const tv_norm_t TV_V1_%d_NORM[] = {" % i)
            for norm in cfg["normalize"]:
                assert 0 <= int(norm["n"]) < 2**63, cfg["name"]
                w("    { %s, UINT64_C(%d) }," % (c_str(norm["input"]), int(norm["n"])))
            w("};")
        w("")

    w("static const tv_config_t TV_V1[] = {")
    for i, cfg in enumerate(configs):
        alphabet = cfg["alphabet"]
        if alphabet == "custom":
            alphabet = cfg["custom_alphabet"]
        invalid = (
            "TV_V1_%d_INVALID, sizeof TV_V1_%d_INVALID / sizeof (char *)" % (i, i)
            if cfg.get("invalid_codes")
            else "NULL, 0"
        )
        norm = (
            "TV_V1_%d_NORM, sizeof TV_V1_%d_NORM / sizeof (tv_norm_t)" % (i, i)
            if cfg.get("normalize")
            else "NULL, 0"
        )
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      %d, %d, %s,"
            % (cfg["min_length"], cfg["max_length"], c_str(cfg["domain"]))
        )
        w(
            "      TV_V1_%d_PAIRS, sizeof TV_V1_%d_PAIRS / sizeof (tv_pair_t),"
            % (i, i)
        )
        w("      %s," % invalid)
        w("      %s }," % norm)
    w("};")
    w("#define TV_V1_COUNT (sizeof TV_V1 / sizeof TV_V1[0])")
    w("")

    out_path.write_text("\n".join(lines) + "\n")
    print("wrote %s (%d NIST vectors, %d v1 configs)" % (out_path, len(nist["vectors"]), len(configs)))


if __name__ == "__main__":
    main()
