#!/usr/bin/env python3
"""Generate C test-vector data (vectors.inc) from testvectors/*.json.

Usage: gen_vectors.py <output.inc>

Reads ../../testvectors/{ff1_nist.json,v1.json,v1c.json,v1r.json} relative
to this script and emits a self-contained C include file with plain
positional aggregate initializers (valid in both C11 and C++17).
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VECTORS_DIR = REPO_ROOT / "testvectors"


def c_str(s):
    if s is None:
        return "NULL"
    out = []
    pending_hex = False  # last emitted item was a \xHH escape
    for b in s.encode("utf-8"):
        ch = chr(b)
        if ch == "\\":
            out.append("\\\\")
            pending_hex = False
        elif ch == '"':
            out.append('\\"')
            pending_hex = False
        elif 0x20 <= b <= 0x7E:
            if pending_hex and ch in "0123456789abcdefABCDEF":
                # C hex escapes are maximal-munch: "\xac" "00" must not
                # merge into \xac00, so split the literal
                out.append('" "')
            out.append(ch)
            pending_hex = False
        else:
            out.append("\\x%02x" % b)
            pending_hex = True
    return '"' + "".join(out) + '"'


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_vectors.py <output.inc>")
    out_path = Path(sys.argv[1])

    nist = json.loads((VECTORS_DIR / "ff1_nist.json").read_text())
    v1 = json.loads((VECTORS_DIR / "v1.json").read_text())
    v1c = json.loads((VECTORS_DIR / "v1c.json").read_text())
    v1r = json.loads((VECTORS_DIR / "v1r.json").read_text())

    lines = []
    w = lines.append
    w("/* Generated by gen_vectors.py from the testvectors JSON files. */")
    w("/* Do not edit by hand. */")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("typedef struct {")
    w("    int sample;")
    w("    const char *key_hex;")
    w("    unsigned radix;")
    w("    const char *tweak_hex;")
    w("    const char *plaintext;")
    w("    const char *ciphertext;")
    w("} tv_nist_t;")
    w("")
    w("static const tv_nist_t TV_NIST[] = {")
    for vec in nist["vectors"]:
        w(
            "    { %d, %s, %d, %s, %s, %s },"
            % (
                vec["sample"],
                c_str(vec["key_hex"]),
                vec["radix"],
                c_str(vec["tweak_hex"]),
                c_str(vec["plaintext"]),
                c_str(vec["ciphertext"]),
            )
        )
    w("};")
    w("#define TV_NIST_COUNT (sizeof TV_NIST / sizeof TV_NIST[0])")
    w("")
    w("typedef struct {")
    w("    uint64_t n;")
    w("    const char *code;")
    w("} tv_pair_t;")
    w("")
    w("typedef struct {")
    w("    const char *input;")
    w("    uint64_t n;")
    w("} tv_norm_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int min_length;")
    w("    int max_length;")
    w("    const char *domain;")
    w("    const tv_pair_t *vectors;")
    w("    size_t n_vectors;")
    w("    const char *const *invalid_codes;")
    w("    size_t n_invalid_codes;")
    w("    const tv_norm_t *normalize;")
    w("    size_t n_normalize;")
    w("    const uint64_t *range_counters;  /* encode must ERR_RANGE these */")
    w("    size_t n_range_counters;")
    w("} tv_config_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int min_length;              /* 0 = default */")
    w("    int max_length;              /* 0 = default */")
    w("    const char *domain;          /* NULL = default */")
    w("} tv_invalid_config_t;")
    w("")

    configs = v1["configs"]
    for i, cfg in enumerate(configs):
        counters = [int(vec["n"]) for vec in cfg["vectors"]]
        assert all(0 <= n < 2**63 for n in counters), cfg["name"]
        w("static const tv_pair_t TV_V1_%d_PAIRS[] = {" % i)
        for vec in cfg["vectors"]:
            w("    { UINT64_C(%d), %s }," % (int(vec["n"]), c_str(vec["code"])))
        w("};")
        if cfg.get("invalid_codes"):
            w("static const char *const TV_V1_%d_INVALID[] = {" % i)
            for code in cfg["invalid_codes"]:
                w("    %s," % c_str(code))
            w("};")
        if cfg.get("normalize"):
            w("static const tv_norm_t TV_V1_%d_NORM[] = {" % i)
            for norm in cfg["normalize"]:
                assert 0 <= int(norm["n"]) < 2**63, cfg["name"]
                w("    { %s, UINT64_C(%d) }," % (c_str(norm["input"]), int(norm["n"])))
            w("};")
        # range_counters are decimal strings; values not representable in
        # uint64_t ("-1", 2^64) cannot even be passed to dealcode_encode(),
        # so the C type system covers them — skip them here.
        range_repr = []
        range_skipped = []
        for s in cfg.get("range_counters", []):
            v = int(s)
            if 0 <= v < 2**64:
                range_repr.append(v)
            else:
                range_skipped.append(s)
        if range_repr:
            if range_skipped:
                w(
                    "/* %s: range counters %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(range_skipped))
                )
            w("static const uint64_t TV_V1_%d_RANGE[] = {" % i)
            for v in range_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        w("")

    w("static const tv_config_t TV_V1[] = {")
    for i, cfg in enumerate(configs):
        alphabet = cfg["alphabet"]
        if alphabet == "custom":
            alphabet = cfg["custom_alphabet"]
        invalid = (
            "TV_V1_%d_INVALID, sizeof TV_V1_%d_INVALID / sizeof (char *)" % (i, i)
            if cfg.get("invalid_codes")
            else "NULL, 0"
        )
        norm = (
            "TV_V1_%d_NORM, sizeof TV_V1_%d_NORM / sizeof (tv_norm_t)" % (i, i)
            if cfg.get("normalize")
            else "NULL, 0"
        )
        has_range = any(
            0 <= int(s) < 2**64 for s in cfg.get("range_counters", [])
        )
        rng = (
            "TV_V1_%d_RANGE, sizeof TV_V1_%d_RANGE / sizeof (uint64_t)" % (i, i)
            if has_range
            else "NULL, 0"
        )
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      %d, %d, %s,"
            % (cfg["min_length"], cfg["max_length"], c_str(cfg["domain"]))
        )
        w(
            "      TV_V1_%d_PAIRS, sizeof TV_V1_%d_PAIRS / sizeof (tv_pair_t),"
            % (i, i)
        )
        w("      %s," % invalid)
        w("      %s," % norm)
        w("      %s }," % rng)
    w("};")
    w("#define TV_V1_COUNT (sizeof TV_V1 / sizeof TV_V1[0])")
    w("")

    invalid_configs = v1.get("invalid_configs", [])
    w("/* Every entry must make construction fail with a config error. */")
    w("static const tv_invalid_config_t TV_V1_INVALID_CONFIGS[] = {")
    for cfg in invalid_configs:
        alphabet = cfg.get("custom_alphabet", cfg.get("alphabet"))
        assert alphabet is not None, cfg["name"]
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      %d, %d, %s },"
            % (
                cfg.get("min_length", 0),
                cfg.get("max_length", 0),
                c_str(cfg.get("domain")),
            )
        )
    w("};")
    w(
        "#define TV_V1_INVALID_CONFIG_COUNT \\"
    )
    w("    (sizeof TV_V1_INVALID_CONFIGS / sizeof TV_V1_INVALID_CONFIGS[0])")
    w("")

    # ---- fixed-length cycling mode (SPEC §11, testvectors/v1c.json) -----
    w("/* Fixed-length cycling mode (SPEC section 11). All decimal-string")
    w(" * fields of v1c.json (n, cycle, capacity, max_cycle) fit uint64_t")
    w(" * by construction (counters < 2^63, capacity <= 2^63); values that")
    w(" * do not (e.g. \"-1\") are skipped below with a comment. */")
    w("")
    w("typedef struct {")
    w("    uint64_t cycle;")
    w("    const char *code;")
    w("} tv_cycle_code_t;")
    w("")
    w("typedef struct {")
    w("    uint64_t cycle;")
    w("    const char *input;")
    w("    uint64_t n;")
    w("} tv_cycle_norm_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int length;")
    w("    const char *domain;")
    w("    uint64_t capacity;           /* radix^length (may be 2^63) */")
    w("    uint64_t max_cycle;          /* (2^63 - 1) / capacity */")
    w("    const tv_pair_t *vectors;")
    w("    size_t n_vectors;")
    w("    const tv_cycle_code_t *invalid_codes;")
    w("    size_t n_invalid_codes;")
    w("    const tv_cycle_norm_t *normalize;")
    w("    size_t n_normalize;")
    w("    const uint64_t *range_counters;  /* encode must ERR_RANGE these */")
    w("    size_t n_range_counters;")
    w("    const uint64_t *invalid_cycles;  /* decode must ERR_RANGE these */")
    w("    size_t n_invalid_cycles;")
    w("} tv_cycle_config_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int length;")
    w("    const char *domain;          /* NULL = default */")
    w("} tv_cycle_invalid_config_t;")
    w("")

    c_configs = v1c["configs"]
    for i, cfg in enumerate(c_configs):
        capacity = int(cfg["capacity"])
        max_cycle = int(cfg["max_cycle"])
        assert 0 < capacity <= 2**63, cfg["name"]
        assert 0 <= max_cycle < 2**63, cfg["name"]
        w("static const tv_pair_t TV_V1C_%d_PAIRS[] = {" % i)
        for vec in cfg["vectors"]:
            n = int(vec["n"])
            assert 0 <= n < 2**63, cfg["name"]
            w("    { UINT64_C(%d), %s }," % (n, c_str(vec["code"])))
        w("};")
        if cfg.get("invalid_codes"):
            w("static const tv_cycle_code_t TV_V1C_%d_INVALID[] = {" % i)
            for entry in cfg["invalid_codes"]:
                cyc = int(entry["cycle"])
                assert 0 <= cyc <= max_cycle, cfg["name"]
                w("    { UINT64_C(%d), %s }," % (cyc, c_str(entry["code"])))
            w("};")
        if cfg.get("normalize"):
            w("static const tv_cycle_norm_t TV_V1C_%d_NORM[] = {" % i)
            for norm in cfg["normalize"]:
                cyc = int(norm["cycle"])
                n = int(norm["n"])
                assert 0 <= cyc <= max_cycle and 0 <= n < 2**63, cfg["name"]
                w(
                    "    { UINT64_C(%d), %s, UINT64_C(%d) },"
                    % (cyc, c_str(norm["input"]), n)
                )
            w("};")
        # range_counters are decimal strings; values not representable in
        # uint64_t ("-1") cannot even be passed to dealcode_cycle_encode(),
        # so the C type system covers them — skip them here.
        range_repr = []
        range_skipped = []
        for s in cfg.get("range_counters", []):
            v = int(s)
            if 0 <= v < 2**64:
                range_repr.append(v)
            else:
                range_skipped.append(s)
        if range_repr:
            if range_skipped:
                w(
                    "/* %s: range counters %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(range_skipped))
                )
            w("static const uint64_t TV_V1C_%d_RANGE[] = {" % i)
            for v in range_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        # invalid_cycles: same uint64_t representability rule ("-1" is
        # unrepresentable and skipped; max_cycle + 1 always fits and MUST
        # remain covered).
        cyc_repr = []
        cyc_skipped = []
        for s in cfg.get("invalid_cycles", []):
            v = int(s)
            if 0 <= v < 2**64:
                cyc_repr.append(v)
            else:
                cyc_skipped.append(s)
        assert max_cycle + 1 in cyc_repr, cfg["name"]
        if cyc_repr:
            if cyc_skipped:
                w(
                    "/* %s: invalid cycles %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(cyc_skipped))
                )
            w("static const uint64_t TV_V1C_%d_BADCYC[] = {" % i)
            for v in cyc_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        w("")

    w("static const tv_cycle_config_t TV_V1C[] = {")
    for i, cfg in enumerate(c_configs):
        alphabet = cfg["alphabet"]
        if alphabet == "custom":
            alphabet = cfg["custom_alphabet"]
        invalid = (
            "TV_V1C_%d_INVALID, "
            "sizeof TV_V1C_%d_INVALID / sizeof (tv_cycle_code_t)" % (i, i)
            if cfg.get("invalid_codes")
            else "NULL, 0"
        )
        norm = (
            "TV_V1C_%d_NORM, sizeof TV_V1C_%d_NORM / sizeof (tv_cycle_norm_t)"
            % (i, i)
            if cfg.get("normalize")
            else "NULL, 0"
        )
        has_range = any(
            0 <= int(s) < 2**64 for s in cfg.get("range_counters", [])
        )
        rng = (
            "TV_V1C_%d_RANGE, sizeof TV_V1C_%d_RANGE / sizeof (uint64_t)"
            % (i, i)
            if has_range
            else "NULL, 0"
        )
        has_badcyc = any(
            0 <= int(s) < 2**64 for s in cfg.get("invalid_cycles", [])
        )
        badcyc = (
            "TV_V1C_%d_BADCYC, sizeof TV_V1C_%d_BADCYC / sizeof (uint64_t)"
            % (i, i)
            if has_badcyc
            else "NULL, 0"
        )
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w("      %d, %s," % (cfg["length"], c_str(cfg["domain"])))
        w(
            "      UINT64_C(%d), UINT64_C(%d),"
            % (int(cfg["capacity"]), int(cfg["max_cycle"]))
        )
        w(
            "      TV_V1C_%d_PAIRS, sizeof TV_V1C_%d_PAIRS / sizeof (tv_pair_t),"
            % (i, i)
        )
        w("      %s," % invalid)
        w("      %s," % norm)
        w("      %s," % rng)
        w("      %s }," % badcyc)
    w("};")
    w("#define TV_V1C_COUNT (sizeof TV_V1C / sizeof TV_V1C[0])")
    w("")

    c_invalid_configs = v1c.get("invalid_configs", [])
    w("/* Every entry must make cycling construction fail with a config"
      " error. */")
    w("static const tv_cycle_invalid_config_t TV_V1C_INVALID_CONFIGS[] = {")
    for cfg in c_invalid_configs:
        alphabet = cfg.get("custom_alphabet", cfg.get("alphabet"))
        assert alphabet is not None, cfg["name"]
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w("      %d, %s }," % (cfg["length"], c_str(cfg.get("domain"))))
    w("};")
    w("#define TV_V1C_INVALID_CONFIG_COUNT \\")
    w("    (sizeof TV_V1C_INVALID_CONFIGS / sizeof TV_V1C_INVALID_CONFIGS[0])")
    w("")

    # ---- integer range mode (SPEC §12, testvectors/v1r.json) ------------
    w("/* Integer range mode (SPEC section 12). All decimal-string fields")
    w(" * of v1r.json (low, high, capacity, n, code) fit uint64_t by")
    w(" * construction (low <= high < 2^63, capacity <= 2^63); values that")
    w(" * do not (e.g. \"-1\", 2^64) are skipped below with a comment. */")
    w("")
    w("typedef struct {")
    w("    uint64_t n;")
    w("    uint64_t code;")
    w("} tv_range_pair_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    uint64_t low;")
    w("    uint64_t high;")
    w("    const char *domain;")
    w("    unsigned radix;              /* expected derived radix */")
    w("    int m;                       /* expected derived numeral count */")
    w("    uint64_t capacity;           /* expected radix^m (may be 2^63) */")
    w("    const tv_range_pair_t *vectors;")
    w("    size_t n_vectors;")
    w("    const uint64_t *invalid_codes;   /* decode: ERR_INVALID_CODE */")
    w("    size_t n_invalid_codes;")
    w("    const uint64_t *range_counters;  /* encode must ERR_RANGE these */")
    w("    size_t n_range_counters;")
    w("} tv_range_config_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    uint64_t low;")
    w("    uint64_t high;")
    w("    const char *domain;          /* NULL = default */")
    w("} tv_range_invalid_config_t;")
    w("")

    r_configs = v1r["configs"]
    for i, cfg in enumerate(r_configs):
        low = int(cfg["low"])
        high = int(cfg["high"])
        capacity = int(cfg["capacity"])
        assert 0 <= low <= high < 2**63, cfg["name"]
        assert int(cfg["radix"]) ** int(cfg["m"]) == capacity, cfg["name"]
        assert 100 <= capacity <= 2**63, cfg["name"]
        w("static const tv_range_pair_t TV_V1R_%d_PAIRS[] = {" % i)
        for vec in cfg["vectors"]:
            n = int(vec["n"])
            code = int(vec["code"])
            assert 0 <= n < capacity and low <= code <= high, cfg["name"]
            w("    { UINT64_C(%d), UINT64_C(%d) }," % (n, code))
        w("};")
        # invalid_codes / range_counters are decimal strings; values not
        # representable in uint64_t ("-1", 2^64) cannot even be passed to
        # the C API, so the type system covers them — skip them here.
        inv_repr = []
        inv_skipped = []
        for s in cfg.get("invalid_codes", []):
            v = int(s)
            if 0 <= v < 2**64:
                inv_repr.append(v)
            else:
                inv_skipped.append(s)
        if inv_repr:
            if inv_skipped:
                w(
                    "/* %s: invalid codes %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(inv_skipped))
                )
            w("static const uint64_t TV_V1R_%d_INVALID[] = {" % i)
            for v in inv_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        range_repr = []
        range_skipped = []
        for s in cfg.get("range_counters", []):
            v = int(s)
            if 0 <= v < 2**64:
                range_repr.append(v)
            else:
                range_skipped.append(s)
        assert capacity in range_repr, cfg["name"]
        if range_repr:
            if range_skipped:
                w(
                    "/* %s: range counters %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(range_skipped))
                )
            w("static const uint64_t TV_V1R_%d_RANGE[] = {" % i)
            for v in range_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        w("")

    w("static const tv_range_config_t TV_V1R[] = {")
    for i, cfg in enumerate(r_configs):
        invalid = (
            "TV_V1R_%d_INVALID, sizeof TV_V1R_%d_INVALID / sizeof (uint64_t)"
            % (i, i)
            if any(0 <= int(s) < 2**64 for s in cfg.get("invalid_codes", []))
            else "NULL, 0"
        )
        rng = (
            "TV_V1R_%d_RANGE, sizeof TV_V1R_%d_RANGE / sizeof (uint64_t)"
            % (i, i)
            if any(0 <= int(s) < 2**64 for s in cfg.get("range_counters", []))
            else "NULL, 0"
        )
        w("    { %s," % c_str(cfg["name"]))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      UINT64_C(%d), UINT64_C(%d), %s,"
            % (int(cfg["low"]), int(cfg["high"]), c_str(cfg["domain"]))
        )
        w(
            "      %d, %d, UINT64_C(%d),"
            % (int(cfg["radix"]), int(cfg["m"]), int(cfg["capacity"]))
        )
        w(
            "      TV_V1R_%d_PAIRS, "
            "sizeof TV_V1R_%d_PAIRS / sizeof (tv_range_pair_t)," % (i, i)
        )
        w("      %s," % invalid)
        w("      %s }," % rng)
    w("};")
    w("#define TV_V1R_COUNT (sizeof TV_V1R / sizeof TV_V1R[0])")
    w("")

    r_invalid_configs = v1r.get("invalid_configs", [])
    r_invalid_emitted = 0
    w("/* Every entry must make range construction fail with a config"
      " error. */")
    w("static const tv_range_invalid_config_t TV_V1R_INVALID_CONFIGS[] = {")
    for cfg in r_invalid_configs:
        low = int(cfg["low"])
        high = int(cfg["high"])
        # low/high not representable in uint64_t (e.g. "-1") cannot even be
        # passed to dealcode_range_new(): the type system covers them.
        if not (0 <= low < 2**64 and 0 <= high < 2**64):
            w(
                "    /* %s skipped: low/high not representable in uint64_t"
                " (covered by the type system) */" % cfg["name"]
            )
            continue
        w("    { %s," % c_str(cfg["name"]))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      UINT64_C(%d), UINT64_C(%d), %s },"
            % (low, high, c_str(cfg.get("domain")))
        )
        r_invalid_emitted += 1
    w("};")
    w("#define TV_V1R_INVALID_CONFIG_COUNT \\")
    w("    (sizeof TV_V1R_INVALID_CONFIGS / sizeof TV_V1R_INVALID_CONFIGS[0])")
    w("")

    out_path.write_text("\n".join(lines) + "\n")
    print(
        "wrote %s (%d NIST vectors, %d v1 configs, %d invalid configs, "
        "%d v1c configs, %d v1c invalid configs, %d v1r configs, "
        "%d v1r invalid configs)"
        % (
            out_path,
            len(nist["vectors"]),
            len(configs),
            len(invalid_configs),
            len(c_configs),
            len(c_invalid_configs),
            len(r_configs),
            r_invalid_emitted,
        )
    )


if __name__ == "__main__":
    main()
