#!/usr/bin/env python3
"""Generate C test-vector data (vectors.inc) from testvectors/*.json.

Usage: gen_vectors.py <output.inc>

Reads ../../testvectors/{ff1_nist.json,v1.json} relative to this script and
emits a self-contained C include file with plain positional aggregate
initializers (valid in both C11 and C++17).
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VECTORS_DIR = REPO_ROOT / "testvectors"


def c_str(s):
    if s is None:
        return "NULL"
    out = []
    pending_hex = False  # last emitted item was a \xHH escape
    for b in s.encode("utf-8"):
        ch = chr(b)
        if ch == "\\":
            out.append("\\\\")
            pending_hex = False
        elif ch == '"':
            out.append('\\"')
            pending_hex = False
        elif 0x20 <= b <= 0x7E:
            if pending_hex and ch in "0123456789abcdefABCDEF":
                # C hex escapes are maximal-munch: "\xac" "00" must not
                # merge into \xac00, so split the literal
                out.append('" "')
            out.append(ch)
            pending_hex = False
        else:
            out.append("\\x%02x" % b)
            pending_hex = True
    return '"' + "".join(out) + '"'


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_vectors.py <output.inc>")
    out_path = Path(sys.argv[1])

    nist = json.loads((VECTORS_DIR / "ff1_nist.json").read_text())
    v1 = json.loads((VECTORS_DIR / "v1.json").read_text())

    lines = []
    w = lines.append
    w("/* Generated by gen_vectors.py from the testvectors JSON files. */")
    w("/* Do not edit by hand. */")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("typedef struct {")
    w("    int sample;")
    w("    const char *key_hex;")
    w("    unsigned radix;")
    w("    const char *tweak_hex;")
    w("    const char *plaintext;")
    w("    const char *ciphertext;")
    w("} tv_nist_t;")
    w("")
    w("static const tv_nist_t TV_NIST[] = {")
    for vec in nist["vectors"]:
        w(
            "    { %d, %s, %d, %s, %s, %s },"
            % (
                vec["sample"],
                c_str(vec["key_hex"]),
                vec["radix"],
                c_str(vec["tweak_hex"]),
                c_str(vec["plaintext"]),
                c_str(vec["ciphertext"]),
            )
        )
    w("};")
    w("#define TV_NIST_COUNT (sizeof TV_NIST / sizeof TV_NIST[0])")
    w("")
    w("typedef struct {")
    w("    uint64_t n;")
    w("    const char *code;")
    w("} tv_pair_t;")
    w("")
    w("typedef struct {")
    w("    const char *input;")
    w("    uint64_t n;")
    w("} tv_norm_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int min_length;")
    w("    int max_length;")
    w("    const char *domain;")
    w("    const tv_pair_t *vectors;")
    w("    size_t n_vectors;")
    w("    const char *const *invalid_codes;")
    w("    size_t n_invalid_codes;")
    w("    const tv_norm_t *normalize;")
    w("    size_t n_normalize;")
    w("    const uint64_t *range_counters;  /* encode must ERR_RANGE these */")
    w("    size_t n_range_counters;")
    w("} tv_config_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *alphabet;        /* preset name, or the custom chars */")
    w("    const char *key_hex;         /* bytes rule, or NULL */")
    w("    const char *key_string;      /* string rule, or NULL */")
    w("    int min_length;              /* 0 = default */")
    w("    int max_length;              /* 0 = default */")
    w("    const char *domain;          /* NULL = default */")
    w("} tv_invalid_config_t;")
    w("")

    configs = v1["configs"]
    for i, cfg in enumerate(configs):
        counters = [int(vec["n"]) for vec in cfg["vectors"]]
        assert all(0 <= n < 2**63 for n in counters), cfg["name"]
        w("static const tv_pair_t TV_V1_%d_PAIRS[] = {" % i)
        for vec in cfg["vectors"]:
            w("    { UINT64_C(%d), %s }," % (int(vec["n"]), c_str(vec["code"])))
        w("};")
        if cfg.get("invalid_codes"):
            w("static const char *const TV_V1_%d_INVALID[] = {" % i)
            for code in cfg["invalid_codes"]:
                w("    %s," % c_str(code))
            w("};")
        if cfg.get("normalize"):
            w("static const tv_norm_t TV_V1_%d_NORM[] = {" % i)
            for norm in cfg["normalize"]:
                assert 0 <= int(norm["n"]) < 2**63, cfg["name"]
                w("    { %s, UINT64_C(%d) }," % (c_str(norm["input"]), int(norm["n"])))
            w("};")
        # range_counters are decimal strings; values not representable in
        # uint64_t ("-1", 2^64) cannot even be passed to dealcode_encode(),
        # so the C type system covers them — skip them here.
        range_repr = []
        range_skipped = []
        for s in cfg.get("range_counters", []):
            v = int(s)
            if 0 <= v < 2**64:
                range_repr.append(v)
            else:
                range_skipped.append(s)
        if range_repr:
            if range_skipped:
                w(
                    "/* %s: range counters %s skipped: not representable in"
                    " uint64_t (covered by the type system) */"
                    % (cfg["name"], ", ".join(range_skipped))
                )
            w("static const uint64_t TV_V1_%d_RANGE[] = {" % i)
            for v in range_repr:
                w("    UINT64_C(%d)," % v)
            w("};")
        w("")

    w("static const tv_config_t TV_V1[] = {")
    for i, cfg in enumerate(configs):
        alphabet = cfg["alphabet"]
        if alphabet == "custom":
            alphabet = cfg["custom_alphabet"]
        invalid = (
            "TV_V1_%d_INVALID, sizeof TV_V1_%d_INVALID / sizeof (char *)" % (i, i)
            if cfg.get("invalid_codes")
            else "NULL, 0"
        )
        norm = (
            "TV_V1_%d_NORM, sizeof TV_V1_%d_NORM / sizeof (tv_norm_t)" % (i, i)
            if cfg.get("normalize")
            else "NULL, 0"
        )
        has_range = any(
            0 <= int(s) < 2**64 for s in cfg.get("range_counters", [])
        )
        rng = (
            "TV_V1_%d_RANGE, sizeof TV_V1_%d_RANGE / sizeof (uint64_t)" % (i, i)
            if has_range
            else "NULL, 0"
        )
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      %d, %d, %s,"
            % (cfg["min_length"], cfg["max_length"], c_str(cfg["domain"]))
        )
        w(
            "      TV_V1_%d_PAIRS, sizeof TV_V1_%d_PAIRS / sizeof (tv_pair_t),"
            % (i, i)
        )
        w("      %s," % invalid)
        w("      %s," % norm)
        w("      %s }," % rng)
    w("};")
    w("#define TV_V1_COUNT (sizeof TV_V1 / sizeof TV_V1[0])")
    w("")

    invalid_configs = v1.get("invalid_configs", [])
    w("/* Every entry must make construction fail with a config error. */")
    w("static const tv_invalid_config_t TV_V1_INVALID_CONFIGS[] = {")
    for cfg in invalid_configs:
        alphabet = cfg.get("custom_alphabet", cfg.get("alphabet"))
        assert alphabet is not None, cfg["name"]
        w("    { %s, %s," % (c_str(cfg["name"]), c_str(alphabet)))
        w("      %s, %s," % (c_str(cfg.get("key_hex")), c_str(cfg.get("key_string"))))
        w(
            "      %d, %d, %s },"
            % (
                cfg.get("min_length", 0),
                cfg.get("max_length", 0),
                c_str(cfg.get("domain")),
            )
        )
    w("};")
    w(
        "#define TV_V1_INVALID_CONFIG_COUNT \\"
    )
    w("    (sizeof TV_V1_INVALID_CONFIGS / sizeof TV_V1_INVALID_CONFIGS[0])")
    w("")

    out_path.write_text("\n".join(lines) + "\n")
    print(
        "wrote %s (%d NIST vectors, %d v1 configs, %d invalid configs)"
        % (out_path, len(nist["vectors"]), len(configs), len(invalid_configs))
    )


if __name__ == "__main__":
    main()
